[build]
  command = "npm run build"
  publish = "examples/simple/out"
  functions = "functions"
  base = "examples/simple"

[dev]
  command = "npm run dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"